# This file is autogenerated, any hand modifications will be lost!

Car-Os.TestApp_path := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/AL/Car-Os.TestApp

APP_LIST :=  $(Car-Os.TestApp_path)

