# This file is autogenerated, any hand modifications will be lost!

Car_Os_TestApp_path := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/AL/Car_Os_TestApp

APP_LIST :=  $(Car_Os_TestApp_path)

