# This file is autogenerated, any hand modifications will be lost!

# Makefile Paths Definitions
CWD := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os
ROOT_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os
CAR_OS_BOARDS_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os\boards/rp2040
MCU_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Mcu
ECUM_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\EcuM
PORT_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Port
DIO_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Dio
SPI_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Spi
LIN_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Lin
ETH_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Eth
ETHIF_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\ECU-AL\EthIf
TCPIP_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\TcpIp
OS_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\Os
OS_BUILDER_PATH := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os\tools\os_builder


# Link Archive File Path Definitions
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Mcu/libMcu.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\EcuM/libEcuM.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Port/libPort.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Dio/libDio.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Spi/libSpi.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Lin/libLin.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\MCAL\Eth/libEth.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\ECU-AL\EthIf/libEthIf.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\TcpIp/libTcpIp.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\SL\Os/libOs.la
E:\LABS\ZEPHYR-LAB\CAR-OS := E:\labs\zephyr-lab\Car-OS.Zephyr/car-os/submodules\AL\NammaTestApp/libNammaTestApp.la


# Link Archive Object List
LA_OBJS :=  $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) \
	    $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS) $(E:\LABS\ZEPHYR-LAB\CAR-OS)
