# This file is autogenerated, any hand modifications will be lost!

# Makefile Paths Definitions
CAR_OS_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os
CAR_OS_INC_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/include
ZEPHYR_INSTALL_PATH := E:/zephyrproject/zephyr/include/zephyr
CAR_OS_BOARD_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/boards/rp2040
MCU_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Mcu
ECUM_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/EcuM
PORT_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Port
DIO_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Dio
SPI_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Spi
LIN_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Lin
ETH_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Eth
ETHIF_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/ECU-AL/EthIf
TCPIP_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/TcpIp
OS_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/Os
OS_BUILDER_PATH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/tools/os_builder


# Link Archive File Path Definitions
LIBMCU := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Mcu/libMcu.la
LIBECUM := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/EcuM/libEcuM.la
LIBPORT := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Port/libPort.la
LIBDIO := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Dio/libDio.la
LIBSPI := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Spi/libSpi.la
LIBLIN := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Lin/libLin.la
LIBETH := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/MCAL/Eth/libEth.la
LIBETHIF := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/ECU-AL/EthIf/libEthIf.la
LIBTCPIP := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/TcpIp/libTcpIp.la
LIBOS := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/SL/Os/libOs.la
LIBCAR_OS_TESTAPP := E:/labs/zephyr-lab/Car-OS.Zephyr/car-os/submodules/AL/Car-Os.TestApp/libCar_OS_TestApp.la


# Link Archive Object List
LA_OBJS :=  $(LIBMCU) $(LIBECUM) $(LIBPORT) $(LIBDIO) $(LIBSPI) $(LIBLIN) $(LIBETH) \
	    $(LIBETHIF) $(LIBTCPIP) $(LIBOS) $(LIBCAR_OS_TESTAPP)
